import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router';
import { Alert, Avatar, Box, Button, Card, CardContent, Chip, Container, Divider, Grid, LinearProgress, Snackbar, Stack, TextField, Typography } from '@mui/material';
import { ApartmentRounded, AutoAwesomeRounded, CheckRounded, DescriptionOutlined, EngineeringRounded, FolderRounded, MailOutlineRounded, PaymentsRounded, PhoneRounded, LocationOnOutlined, SecurityRounded, SmartphoneRounded, VerifiedUserRounded } from '@mui/icons-material';
import { useSite } from '../context/SiteContext';
import { submitSiteEnquiry } from '../services/api';

const iconMap: Record<string, any> = {
  verifieduser: VerifiedUserRounded, verified_user: VerifiedUserRounded, apartment: ApartmentRounded, payments: PaymentsRounded,
  folder: FolderRounded, engineering: EngineeringRounded, smartphone: SmartphoneRounded, security: SecurityRounded, description: DescriptionOutlined,
};
const normalize = (value = '') => value.toLowerCase().replace(/[^a-z0-9_]/g, '');

function SectionHeading({ title, subtitle }: { title?: string; subtitle?: string }) {
  return <Box sx={{ textAlign: 'center', mb: 6 }}><Typography sx={{ fontWeight: 950, fontSize: { xs: '2rem', md: '2.8rem' }, letterSpacing: '-.04em' }}>{title}</Typography>{subtitle && <Typography sx={{ color: 'text.secondary', maxWidth: 720, mx: 'auto', mt: 1.5, lineHeight: 1.7 }}>{subtitle}</Typography>}</Box>;
}

function DynamicSections({ sections }: { sections: any[] }) {
  const { data } = useSite(); const navigate = useNavigate(); const primary = data.settings?.brand?.primaryColor || '#0B5270';
  return <>{[...sections].filter((section) => section.active !== false).sort((a, b) => Number(a.sortOrder || 0) - Number(b.sortOrder || 0)).map((section) => {
    const items = Array.isArray(section.content?.items) ? section.content.items : [];
    if (section.type === 'rich_text') return <Container key={section.key} maxWidth="md" sx={{ py: 7 }}><Typography variant="h3" sx={{ fontWeight: 950, letterSpacing: '-.04em' }}>{section.title}</Typography>{section.subtitle && <Typography color="text.secondary" sx={{ mt: 1 }}>{section.subtitle}</Typography>}<Stack spacing={2} sx={{ mt: 3 }}>{(section.content?.paragraphs || []).map((paragraph: string, index: number) => <Typography key={index} sx={{ lineHeight: 1.85, color: 'text.secondary', fontSize: '1.02rem' }}>{paragraph}</Typography>)}</Stack></Container>;
    if (section.type === 'feature_list' || section.type === 'features') return <Container key={section.key} maxWidth="lg" sx={{ py: 8 }}><SectionHeading title={section.title} subtitle={section.subtitle} /><Grid container spacing={2.5}>{items.map((item: any, index: number) => { const object = typeof item === 'string' ? { title: item } : item; const Icon = iconMap[normalize(object.icon)] || AutoAwesomeRounded; return <Grid size={{ xs: 12, sm: 6, md: 4 }} key={`${object.title}-${index}`}><Card elevation={0} sx={{ height: '100%', border: '1px solid', borderColor: 'divider', borderRadius: 4 }}><CardContent sx={{ p: 3.5 }}><Box sx={{ width: 48, height: 48, display: 'grid', placeItems: 'center', bgcolor: `${primary}12`, color: primary, borderRadius: 3, mb: 2 }}><Icon /></Box><Typography sx={{ fontWeight: 850 }}>{object.title}</Typography>{(object.description || object.desc) && <Typography color="text.secondary" sx={{ mt: 1, lineHeight: 1.7 }}>{object.description || object.desc}</Typography>}</CardContent></Card></Grid>; })}</Grid></Container>;
    if (section.type === 'stats') return <Box key={section.key} sx={{ bgcolor: primary, color: 'white', py: 4 }}><Container maxWidth="lg"><Grid container spacing={2}>{items.map((item: any, index: number) => <Grid size={{ xs: 6, md: 3 }} key={`${item.label}-${index}`}><Box sx={{ textAlign: 'center' }}><Typography sx={{ fontWeight: 950, fontSize: { xs: '1.3rem', md: '1.8rem' } }}>{item.value}</Typography><Typography sx={{ opacity: .72, fontSize: '.78rem' }}>{item.label}</Typography></Box></Grid>)}</Grid></Container></Box>;
    if (section.type === 'featured_properties') return <Container key={section.key} maxWidth="xl" sx={{ py: 8 }}><SectionHeading title={section.title} subtitle={section.subtitle} /><Grid container spacing={2.5}>{(data.featuredProperties || []).slice(0, Number(section.content?.limit || 6)).map((property: any) => <Grid size={{ xs: 12, sm: 6, lg: 4 }} key={property._id}><Card onClick={() => navigate(`/marketplace/${property._id}`)} elevation={0} sx={{ cursor: 'pointer', height: '100%', border: '1px solid', borderColor: 'divider', borderRadius: 4, overflow: 'hidden' }}><Box component="img" src={property.galleryCover || property.images?.[0] || '/placeholder-property.svg'} alt={property.title} sx={{ width: '100%', height: 220, objectFit: 'cover', bgcolor: 'action.hover' }} /><CardContent><Stack direction="row" justifyContent="space-between" gap={1}><Typography sx={{ fontWeight: 900 }}>{property.title}</Typography><Chip size="small" label={property.purpose || property.listingType} /></Stack><Typography color="text.secondary" sx={{ mt: .7 }}>{property.address?.city || property.map?.locality || 'Location available on request'}</Typography><Typography sx={{ mt: 1.5, fontWeight: 900, color: primary }}>₹{Number(property.price || property.pricing?.monthlyRent || property.pricing?.salePrice || 0).toLocaleString('en-IN')}</Typography></CardContent></Card></Grid>)}{!data.featuredProperties?.length && <Grid size={12}><Alert severity="info">Featured properties will appear here when administrators or eligible landlords publish promotions.</Alert></Grid>}</Grid></Container>;
    if (section.type === 'featured_surveyors') return <Container key={section.key} maxWidth="xl" sx={{ py: 8 }}><SectionHeading title={section.title} subtitle={section.subtitle} /><Grid container spacing={2.5}>{(data.featuredSurveyors || []).slice(0, Number(section.content?.limit || 6)).map((profile: any) => <Grid size={{ xs: 12, sm: 6, lg: 4 }} key={profile._id}><Card onClick={() => navigate(`/surveyors/${profile.publicSlug || profile._id}`)} elevation={0} sx={{ cursor: 'pointer', height: '100%', border: '1px solid', borderColor: 'divider', borderRadius: 4 }}><CardContent sx={{ p: 3 }}><Stack direction="row" gap={2}><Avatar src={profile.profilePhoto} sx={{ width: 64, height: 64 }}>{profile.name?.[0]}</Avatar><Box><Stack direction="row" gap={1} alignItems="center"><Typography sx={{ fontWeight: 900 }}>{profile.name}</Typography>{profile.verificationStatus === 'verified' && <VerifiedUserRounded color="primary" fontSize="small" />}</Stack><Typography color="text.secondary">{profile.professionalTitle || profile.profileType}</Typography><Typography sx={{ mt: 1, fontWeight: 750 }}>From ₹{Number(profile.startingPrice || 0).toLocaleString('en-IN')}</Typography></Box></Stack></CardContent></Card></Grid>)}{!data.featuredSurveyors?.length && <Grid size={12}><Alert severity="info">Verified public surveyor profiles will appear here.</Alert></Grid>}</Grid></Container>;
    if (section.type === 'cta') return <Box key={section.key} sx={{ py: 8, bgcolor: 'action.hover' }}><Container maxWidth="md" sx={{ textAlign: 'center' }}><Typography variant="h3" sx={{ fontWeight: 950 }}>{section.title}</Typography><Typography color="text.secondary" sx={{ mt: 1.5 }}>{section.subtitle}</Typography><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="center" gap={1.5} sx={{ mt: 3 }}><Button variant="contained" href={section.content?.primaryUrl || '/login'}>{section.content?.primaryLabel || 'Get started'}</Button>{section.content?.secondaryLabel && <Button variant="outlined" href={section.content?.secondaryUrl || '/marketplace'}>{section.content.secondaryLabel}</Button>}</Stack></Container></Box>;
    return null;
  })}</>;
}

export function Home() {
  const { data, loading } = useSite(); const settings = data.settings || {}; const slides = data.carousel || []; const [index, setIndex] = useState(0); const primary = settings.brand?.primaryColor || '#0B5270';
  useEffect(() => { if (slides.length < 2) return; const timer = window.setInterval(() => setIndex((value) => (value + 1) % slides.length), 6000); return () => window.clearInterval(timer); }, [slides.length]);
  const slide = slides[index];
  return <Box sx={{ bgcolor: 'background.default' }}>{loading && <LinearProgress />}{settings.homepage?.heroEnabled !== false && <Box sx={{ minHeight: { xs: 560, md: 650 }, display: 'grid', placeItems: 'center', position: 'relative', overflow: 'hidden', color: slide?.imageUrl ? 'white' : 'text.primary', bgcolor: slide?.imageUrl ? '#0f172a' : 'background.paper' }}>{slide?.imageUrl && <Box component="img" src={slide.imageUrl} alt={slide.altText || slide.title} sx={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover' }} />}{slide?.imageUrl && <Box sx={{ position: 'absolute', inset: 0, bgcolor: `rgba(2,8,23,${slide.overlay?.enabled === false ? 0 : slide.overlay?.opacity ?? .45})` }} />}<Container maxWidth="lg" sx={{ position: 'relative', zIndex: 1, textAlign: slide?.textAlign || 'center', py: 10 }}><Chip label={slide?.eyebrow || settings.homepage?.eyebrow || settings.shortTitle || settings.siteTitle} sx={{ mb: 3, bgcolor: slide?.imageUrl ? 'rgba(255,255,255,.14)' : `${primary}14`, color: slide?.imageUrl ? 'white' : primary, fontWeight: 850 }} /><Typography variant="h1" sx={{ maxWidth: 960, mx: slide?.textAlign === 'left' ? 0 : 'auto', fontWeight: 950, letterSpacing: '-.05em', fontSize: { xs: '2.7rem', md: '4.8rem' }, lineHeight: 1.04 }}>{slide?.title || settings.tagline || settings.siteTitle}</Typography><Typography sx={{ maxWidth: 760, mx: slide?.textAlign === 'left' ? 0 : 'auto', mt: 3, fontSize: { xs: '1rem', md: '1.2rem' }, lineHeight: 1.7, color: slide?.imageUrl ? 'rgba(255,255,255,.8)' : 'text.secondary' }}>{slide?.subtitle || settings.description}</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} justifyContent={slide?.textAlign === 'left' ? 'flex-start' : 'center'} sx={{ mt: 5 }}><Button variant="contained" size="large" href={slide?.primaryCta?.url || '/marketplace'}>{slide?.primaryCta?.label || 'Browse properties'}</Button><Button variant="outlined" size="large" href={slide?.secondaryCta?.url || '/login'} sx={{ color: slide?.imageUrl ? 'white' : primary, borderColor: slide?.imageUrl ? 'rgba(255,255,255,.45)' : undefined }}>{slide?.secondaryCta?.label || 'Open dashboard'}</Button></Stack>{slides.length > 1 && <Stack direction="row" spacing={1} justifyContent={slide?.textAlign === 'left' ? 'flex-start' : 'center'} sx={{ mt: 5 }}>{slides.map((_item, dot) => <Box key={dot} onClick={() => setIndex(dot)} sx={{ width: dot === index ? 28 : 9, height: 9, borderRadius: 99, cursor: 'pointer', bgcolor: dot === index ? primary : 'rgba(148,163,184,.6)' }} />)}</Stack>}</Container></Box>}<DynamicSections sections={data.sections || []} /></Box>;
}

export function Pricing() {
  const { data } = useSite(); const plans = data.landlordPlans || []; const primary = data.settings?.brand?.primaryColor || '#0B5270';
  return <Box sx={{ bgcolor: 'background.default', minHeight: '100vh' }}><Box sx={{ bgcolor: primary, py: { xs: 6, md: 8 }, textAlign: 'center', color: 'white' }}><Container maxWidth="md"><Typography sx={{ fontWeight: 950, fontSize: { xs: '2.1rem', md: '3rem' } }}>{data.page?.hero?.title || data.page?.title || 'Landlord subscription plans'}</Typography><Typography sx={{ mt: 1.5, opacity: .75 }}>{data.page?.hero?.subtitle || 'Limits and capabilities are configured by administrators in MongoDB.'}</Typography></Container></Box><Container maxWidth="xl" sx={{ py: { xs: 6, md: 10 } }}><Grid container spacing={3}>{plans.map((plan: any) => <Grid size={{ xs: 12, md: 6, lg: 3 }} key={plan.key}><Card elevation={0} sx={{ height: '100%', borderRadius: 4, border: plan.featured ? `2px solid ${primary}` : '1px solid', borderColor: plan.featured ? primary : 'divider', position: 'relative' }}>{plan.featured && <Chip label="Recommended" sx={{ position: 'absolute', top: -14, left: '50%', transform: 'translateX(-50%)', bgcolor: primary, color: 'white' }} />}<CardContent sx={{ p: 3.5 }}><Typography sx={{ fontWeight: 950, fontSize: '1.25rem' }}>{plan.name}</Typography><Typography color="text.secondary" sx={{ minHeight: 62, mt: 1 }}>{plan.description}</Typography><Typography sx={{ fontWeight: 950, fontSize: '2.1rem', mt: 2, color: primary }}>{plan.key === 'enterprise' ? 'Custom' : `₹${Number(plan.prices?.monthly || 0).toLocaleString('en-IN')}`}<Typography component="span" color="text.secondary" sx={{ fontSize: '.85rem' }}>{plan.key === 'enterprise' ? '' : '/month'}</Typography></Typography><Divider sx={{ my: 2.5 }} /><Stack spacing={1.1}>{Object.entries(plan.limits || {}).filter(([, value]) => ['string','number','boolean'].includes(typeof value)).slice(0, 10).map(([label, value]) => <Stack direction="row" spacing={1} key={label}><CheckRounded sx={{ color: primary, fontSize: 18 }} /><Typography sx={{ fontSize: '.86rem' }}>{label.replace(/([A-Z])/g, ' $1')}: <b>{typeof value === 'boolean' ? (value ? 'Included' : 'Not included') : Number(value) >= 999999 ? 'Unlimited' : String(value)}</b></Typography></Stack>)}</Stack><Button href="/login" fullWidth variant={plan.featured ? 'contained' : 'outlined'} sx={{ mt: 3 }}>{plan.key === 'enterprise' ? 'Contact sales' : 'Choose plan'}</Button></CardContent></Card></Grid>)}{!plans.length && <Grid size={12}><Alert severity="info">Subscription plans are being configured.</Alert></Grid>}</Grid></Container></Box>;
}

export function DynamicContentPage() {
  const { data, loading } = useSite(); const page = data.page; const primary = data.settings?.brand?.primaryColor || '#0B5270';
  if (loading) return <LinearProgress />;
  if (!page) return <Container maxWidth="md" sx={{ py: 12 }}><Alert severity="warning">This page is not published.</Alert></Container>;
  return <Box sx={{ minHeight: '100vh', bgcolor: 'background.default' }}><Box sx={{ bgcolor: primary, color: 'white', py: { xs: 7, md: 10 } }}><Container maxWidth="md"><Chip label={page.hero?.eyebrow || page.subtitle || page.title} sx={{ mb: 2, bgcolor: 'rgba(255,255,255,.15)', color: 'white' }} /><Typography sx={{ fontWeight: 950, fontSize: { xs: '2.2rem', md: '3.4rem' }, letterSpacing: '-.04em' }}>{page.hero?.title || page.title}</Typography>{(page.hero?.subtitle || page.subtitle) && <Typography sx={{ mt: 2, opacity: .78, fontSize: '1.05rem', lineHeight: 1.7 }}>{page.hero?.subtitle || page.subtitle}</Typography>}</Container></Box><DynamicSections sections={page.sections || []} /></Box>;
}
export const About = DynamicContentPage;

export function Contact() {
  const { data } = useSite(); const settings = data.settings || {}; const page = data.page; const primary = settings.brand?.primaryColor || '#0B5270'; const [form, setForm] = useState({ name: '', email: '', phone: '', message: '' }); const [sending, setSending] = useState(false); const [notice, setNotice] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setSending(true); try { await submitSiteEnquiry(form); setNotice('Your message has been submitted.'); setForm({ name: '', email: '', phone: '', message: '' }); } catch (error) { setNotice((error as Error).message); } finally { setSending(false); } }
  const contactItems = useMemo(() => [{ icon: MailOutlineRounded, label: 'Email', value: settings.contact?.email }, { icon: PhoneRounded, label: 'Phone', value: settings.contact?.phone }, { icon: LocationOnOutlined, label: 'Address', value: settings.contact?.address }].filter((item) => item.value), [settings.contact]);
  return <Box sx={{ bgcolor: 'background.default', minHeight: '100vh' }}><Box sx={{ bgcolor: primary, color: 'white', py: { xs: 7, md: 9 } }}><Container maxWidth="md"><Typography sx={{ fontWeight: 950, fontSize: { xs: '2.2rem', md: '3.1rem' } }}>{page?.hero?.title || page?.title || 'Contact'}</Typography><Typography sx={{ mt: 1.5, opacity: .75 }}>{page?.hero?.subtitle || page?.subtitle}</Typography></Container></Box><Container maxWidth="lg" sx={{ py: { xs: 7, md: 10 } }}><Grid container spacing={6}><Grid size={{ xs: 12, md: 5 }}><Stack spacing={3}>{contactItems.map((item) => <Stack direction="row" spacing={2} key={item.label}><Box sx={{ width: 44, height: 44, borderRadius: 3, bgcolor: `${primary}12`, color: primary, display: 'grid', placeItems: 'center' }}><item.icon /></Box><Box><Typography variant="overline" color="text.secondary">{item.label}</Typography><Typography sx={{ fontWeight: 750 }}>{item.value}</Typography></Box></Stack>)}</Stack></Grid><Grid size={{ xs: 12, md: 7 }}><Card elevation={0} sx={{ border: '1px solid', borderColor: 'divider', borderRadius: 4 }}><CardContent sx={{ p: { xs: 3, md: 4 } }}><Box component="form" onSubmit={submit}><Grid container spacing={2}><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth required label="Full name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth label="Phone" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></Grid><Grid size={12}><TextField fullWidth label="Email" type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></Grid><Grid size={12}><TextField fullWidth required multiline rows={5} label="Message" value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} /></Grid><Grid size={12}><Button disabled={sending} type="submit" variant="contained" size="large">{sending ? 'Submitting…' : 'Send message'}</Button></Grid></Grid></Box></CardContent></Card></Grid></Grid></Container><Snackbar open={Boolean(notice)} autoHideDuration={5000} onClose={() => setNotice('')}><Alert severity={notice.includes('submitted') ? 'success' : 'error'}>{notice}</Alert></Snackbar></Box>;
}
