import { useEffect, useState } from 'react';
import { Alert, Avatar, Box, Button, Card, CardContent, Chip, CircularProgress, Container, Grid, Paper, Stack, TextField, Typography } from '@mui/material';
import { LockRounded } from '@mui/icons-material';
import { useParams, useSearchParams } from 'react-router';
import { getPrivateSurveyor } from '../services/api';
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0);
export default function SurveyorPrivateProfilePage(){
 const{id=''}=useParams();const[q]=useSearchParams();const token=q.get('token')||'';const[data,setData]=useState<any>();const[error,setError]=useState('');const[code,setCode]=useState(q.get('code')||'');const[loading,setLoading]=useState(true);
 async function load(nextCode=code){setLoading(true);setError('');try{const r=await getPrivateSurveyor(id,token,nextCode);setData(r.data)}catch(e){setData(undefined);setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{load(q.get('code')||'')},[id,token]);
 if(loading)return <Box sx={{minHeight:'70vh',display:'grid',placeItems:'center'}}><CircularProgress/></Box>;
 if(error)return <Container maxWidth="sm" sx={{pt:14}}><Paper elevation={0} sx={{p:3,border:'1px solid',borderColor:'divider',borderRadius:4}}><Alert severity="warning" sx={{mb:2}}>{error}</Alert><Typography sx={{fontWeight:900,mb:1}}>Private profile access</Typography><Typography color="text.secondary" sx={{fontSize:13,mb:2}}>Enter the access code supplied by the surveyor. The share token must also be valid and not revoked.</Typography><Stack direction={{xs:'column',sm:'row'}} spacing={1}><TextField fullWidth size="small" type="password" label="Access code" value={code} onChange={(e)=>setCode(e.target.value)} onKeyDown={(e)=>e.key==='Enter'&&load(code)}/><Button variant="contained" onClick={()=>load(code)}>Open profile</Button></Stack></Paper></Container>;
 if(!data)return null;
 return <Box sx={{pt:12,pb:8,minHeight:'100vh',bgcolor:'background.default'}}><Container maxWidth="md"><Alert icon={<LockRounded/>} severity="info" sx={{mb:2}}>Private professional profile. This link can be password-protected or revoked by the surveyor.</Alert><Paper elevation={0} sx={{p:{xs:2,md:4},border:'1px solid',borderColor:'divider',borderRadius:5}}><Stack direction={{xs:'column',sm:'row'}} spacing={2}><Avatar src={data.profilePhoto||data.agencyLogo} sx={{width:90,height:90,bgcolor:'primary.main'}}>{data.name?.[0]}</Avatar><Box><Typography variant="h4" sx={{fontWeight:950}}>{data.name}</Typography><Typography color="text.secondary">{data.professionalTitle||data.profileType}</Typography><Stack direction="row" spacing={1} sx={{mt:1}}><Chip label={`${data.yearsExperience||0}+ years`}/><Chip label={data.availability}/></Stack></Box></Stack><Typography color="text.secondary" sx={{mt:3,lineHeight:1.8}}>{data.description}</Typography><Grid container spacing={2} sx={{mt:1}}>{(data.services||[]).map((s:any)=><Grid size={{ xs: 12, sm: 6 }} key={s._id}><Card elevation={0} sx={{border:'1px solid',borderColor:'divider',borderRadius:4}}><CardContent><Typography sx={{fontWeight:900}}>{s.title}</Typography><Typography color="text.secondary" sx={{fontSize:12,mt:1}}>{s.shortDescription||s.description}</Typography><Typography sx={{fontWeight:900,mt:2}}>{money(s.startingPrice)}</Typography></CardContent></Card></Grid>)}</Grid></Paper></Container></Box>;
}
