import { useEffect, useState } from 'react';
import { Alert, Box, Button, Chip, CircularProgress, FormControlLabel, Paper, Stack, Switch, TextField, Typography } from '@mui/material';
import { AdminPanelSettingsRounded, FolderSharedRounded, GavelRounded, SecurityRounded, StorageRounded } from '@mui/icons-material';
import { toast } from 'sonner';
import { getDriveAdminOverview, getDriveAdminReports, getDriveAdminUsage, getDrivePolicy, reviewDriveContentReport, updateDrivePolicy } from '../../services/api';

function formatBytes(bytes = 0) { if (!bytes) return '0 B'; const units = ['B','KB','MB','GB','TB']; const i = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1); return `${(bytes / 1024 ** i).toFixed(i > 1 ? 1 : 0)} ${units[i]}`; }
export default function DriveAdministrationPage() {
  const [loading, setLoading] = useState(true); const [overview, setOverview] = useState<any>({}); const [usage, setUsage] = useState<any[]>([]); const [reports, setReports] = useState<any[]>([]); const [policy, setPolicy] = useState<any>({});
  async function load() { setLoading(true); try { const [a,b,c,d] = await Promise.all([getDriveAdminOverview(), getDriveAdminUsage(), getDriveAdminReports(), getDrivePolicy()]); setOverview(a.data); setUsage(b.data); setReports(c.data); setPolicy(d.data); } catch (e:any) { toast.error(e.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function savePolicy() { try { setPolicy((await updateDrivePolicy(policy)).data); toast.success('Drive policy updated'); } catch (e:any) { toast.error(e.message); } }
  if (loading) return <Box sx={{ minHeight: 500, display: 'grid', placeItems: 'center' }}><CircularProgress /></Box>;
  const cards = [
    ['Storage used', formatBytes(overview.usage?.usedBytes), StorageRounded], ['Drive users', overview.usage?.users || 0, AdminPanelSettingsRounded], ['Public files', overview.publicFiles || 0, FolderSharedRounded], ['Open reports', overview.openReports || 0, GavelRounded],
  ] as const;
  return <Box sx={{ px: { xs: 2, sm: 3, lg: 4 }, pb: 5 }}><Typography variant="h4" sx={{ fontWeight: 900 }}>Drive Administration</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Storage policy, public-sharing compliance, user usage and reported content.</Typography>
    <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(210px,1fr))', gap: 1.5, mb: 2.5 }}>{cards.map(([label,value,Icon]) => <Paper key={label} sx={{ p: 2.2, borderRadius: 4 }}><Icon color="primary" /><Typography variant="h5" sx={{ fontWeight: 900, mt: 1 }}>{value}</Typography><Typography color="text.secondary" variant="body2">{label}</Typography></Paper>)}</Box>
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', xl: '1fr 1fr' }, gap: 2 }}>
      <Paper sx={{ p: 2.5, borderRadius: 4 }}><Stack direction="row" alignItems="center" gap={1}><SecurityRounded color="primary" /><Typography variant="h6" sx={{ fontWeight: 900 }}>Platform drive policy</Typography></Stack><Stack gap={2} sx={{ mt: 2 }}><TextField label="Maximum file size (MB)" type="number" value={policy.maxFileMb || 250} onChange={(e) => setPolicy({ ...policy, maxFileMb: Number(e.target.value) })} /><TextField label="Trash retention (days)" type="number" value={policy.trashRetentionDays || 60} onChange={(e) => setPolicy({ ...policy, trashRetentionDays: Number(e.target.value) })} /><TextField label="Legal retention (days)" type="number" value={policy.legalRetentionDays || 2555} onChange={(e) => setPolicy({ ...policy, legalRetentionDays: Number(e.target.value) })} /><TextField label="Allowed extensions" multiline minRows={3} value={(policy.allowedExtensions || []).join(',')} onChange={(e) => setPolicy({ ...policy, allowedExtensions: e.target.value.split(',').map((x) => x.trim()).filter(Boolean) })} /><FormControlLabel control={<Switch checked={Boolean(policy.publicSharingEnabled)} onChange={(e) => setPolicy({ ...policy, publicSharingEnabled: e.target.checked })} />} label="Allow public sharing" /><FormControlLabel control={<Switch checked={Boolean(policy.legalPublicSharingEnabled)} onChange={(e) => setPolicy({ ...policy, legalPublicSharingEnabled: e.target.checked })} />} label="Allow public sharing of sensitive legal records with confirmation" /><FormControlLabel control={<Switch checked={Boolean(policy.malwareScanRequired)} onChange={(e) => setPolicy({ ...policy, malwareScanRequired: e.target.checked })} />} label="Require ClamAV malware scanning" /><Button variant="contained" onClick={savePolicy}>Save policy</Button></Stack></Paper>
      <Paper sx={{ p: 2.5, borderRadius: 4 }}><Typography variant="h6" sx={{ fontWeight: 900 }}>Reported public content</Typography>{reports.length === 0 ? <Alert severity="success" sx={{ mt: 2 }}>No public-content reports need review.</Alert> : reports.map((report) => <Paper key={report._id} variant="outlined" sx={{ p: 1.5, mt: 1.2, borderRadius: 3 }}><Stack direction="row" justifyContent="space-between" gap={2}><Box><Typography sx={{ fontWeight: 800, textTransform: 'capitalize' }}>{report.reason.replaceAll('_',' ')}</Typography><Typography variant="body2" color="text.secondary">{report.details || 'No additional details'}</Typography></Box><Chip size="small" label={report.status} /></Stack><Stack direction="row" gap={1} sx={{ mt: 1.3 }}><Button size="small" variant="outlined" onClick={() => reviewDriveContentReport(report._id, { status: 'dismissed', decision: 'No policy violation found' }).then(load)}>Dismiss</Button><Button size="small" variant="contained" color="error" onClick={() => reviewDriveContentReport(report._id, { status: 'restricted', decision: 'Restricted pending compliance review', restrict: true }).then(load)}>Restrict content</Button></Stack></Paper>)}</Paper>
    </Box>
    <Paper sx={{ p: 2.5, borderRadius: 4, mt: 2 }}><Typography variant="h6" sx={{ fontWeight: 900, mb: 1.5 }}>Highest storage usage</Typography><Box sx={{ overflowX: 'auto' }}><Box sx={{ minWidth: 700 }}>{usage.slice(0, 50).map((row) => <Box key={row._id} sx={{ py: 1.2, display: 'grid', gridTemplateColumns: 'minmax(220px,1fr) 150px 150px 120px', borderBottom: '1px solid', borderColor: 'divider' }}><Box><Typography sx={{ fontWeight: 750 }}>{row.user?.name || 'Deleted user'}</Typography><Typography variant="caption" color="text.secondary">{row.user?.email}</Typography></Box><Typography>{formatBytes(row.usedBytes)}</Typography><Typography>{formatBytes(row.trashBytes)}</Typography><Chip size="small" label={row.user?.role || 'unknown'} sx={{ justifySelf: 'start' }} /></Box>)}</Box></Box></Paper>
  </Box>;
}
