import { useEffect, useState } from 'react';
import {
  Alert, Box, Button, Card, CardContent, Chip, CircularProgress, DialogActions, DialogContent, DialogTitle,
  Divider, Grid, IconButton, List, ListItem, ListItemText, Paper, Stack, TextField, Typography,
} from '@mui/material';
import ProfessionalDialog from '../../components/shared/ProfessionalDialog';
import { ContentCopyRounded, DeleteOutlineRounded, PasswordRounded, RefreshRounded, SecurityRounded } from '@mui/icons-material';
import {
  beginTwoFactorSetup, changePassword, disableTwoFactor, enableTwoFactor, getSecurityOverview,
  regenerateBackupCodes, revokeOtherSessions, revokeSession,
} from '../../services/api';

type Session = { id:string; device?:string; ip?:string; createdAt?:string; lastUsedAt?:string; expiresAt?:string; current?:boolean };

export default function SecurityPage(){
  const [data,setData]=useState<{twoFactorEnabled:boolean;sessions:Session[]}>({twoFactorEnabled:false,sessions:[]}); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  const [passwordDialog,setPasswordDialog]=useState(false); const [currentPassword,setCurrentPassword]=useState(''); const [newPassword,setNewPassword]=useState('');
  const [setup,setSetup]=useState<{secret:string;otpauthUri:string}|null>(null); const [code,setCode]=useState(''); const [password,setPassword]=useState(''); const [backupCodes,setBackupCodes]=useState<string[]>([]);
  async function load(){setLoading(true);try{setData((await getSecurityOverview()).data);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  async function run(action:()=>Promise<any>,success:string){setError('');setMessage('');try{await action();setMessage(success);await load();}catch(e){setError((e as Error).message);}}
  async function startSetup(){setError('');try{setSetup((await beginTwoFactorSetup()).data);setCode('');setPassword('');setBackupCodes([]);}catch(e){setError((e as Error).message);}}
  async function enable(){setError('');try{const result=await enableTwoFactor(password,code);setBackupCodes(result.data.backupCodes);setSetup(null);setCode('');setPassword('');setMessage('Two-factor authentication enabled. Save the backup codes now.');await load();}catch(e){setError((e as Error).message);}}
  async function copy(text:string){await navigator.clipboard.writeText(text);setMessage('Copied to clipboard');}
  if(loading)return <Box sx={{py:12,display:'grid',placeItems:'center'}}><CircularProgress/></Box>;
  return <Box sx={{px:{xs:2,sm:3,lg:4},pb:6}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" mb={3}><Box><Typography variant="h4" fontWeight={950}>Security & Sessions</Typography><Typography color="text.secondary">Password, two-factor authentication and signed-in devices are protected by MongoDB-backed session records.</Typography></Box><Button startIcon={<RefreshRounded/>} onClick={load}>Refresh</Button></Stack>
    {error&&<Alert severity="error" onClose={()=>setError('')} sx={{mb:2}}>{error}</Alert>}{message&&<Alert severity="success" onClose={()=>setMessage('')} sx={{mb:2}}>{message}</Alert>}
    {backupCodes.length>0&&<Alert severity="warning" sx={{mb:2}}><Typography fontWeight={900}>Store these one-time backup codes securely.</Typography><Stack direction="row" flexWrap="wrap" gap={1} mt={1}>{backupCodes.map(item=><Chip key={item} label={item} onDelete={()=>void copy(item)} deleteIcon={<ContentCopyRounded/>}/>)}</Stack></Alert>}
    <Grid container spacing={2}><Grid size={{xs:12,lg:5}}><Card variant="outlined" sx={{borderRadius:4,height:'100%'}}><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography variant="h6" fontWeight={900}>Account protection</Typography><Typography color="text.secondary" fontSize={13}>Use a strong password and authenticator verification.</Typography></Box><SecurityRounded color={data.twoFactorEnabled?'success':'disabled'}/></Stack><Divider sx={{my:2}}/><Stack spacing={2}><Button variant="outlined" startIcon={<PasswordRounded/>} onClick={()=>setPasswordDialog(true)}>Change password</Button>{data.twoFactorEnabled?<><Chip color="success" label="Two-factor authentication enabled"/><TextField label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><TextField label="Authenticator or backup code" value={code} onChange={e=>setCode(e.target.value)}/><Stack direction={{xs:'column',sm:'row'}} spacing={1}><Button color="error" variant="outlined" onClick={()=>run(()=>disableTwoFactor(password,code),'Two-factor authentication disabled')}>Disable 2FA</Button><Button variant="outlined" onClick={async()=>{try{const result=await regenerateBackupCodes(password,code);setBackupCodes(result.data.backupCodes);setMessage('Backup codes regenerated.');}catch(e){setError((e as Error).message);}}}>New backup codes</Button></Stack></>:setup?<Stack spacing={1.5}><Alert severity="info">Add this account to your authenticator app, then enter the current six-digit code.</Alert><Paper variant="outlined" sx={{p:2,borderRadius:3,wordBreak:'break-all'}}><Typography fontSize={12} color="text.secondary">Secret</Typography><Typography fontFamily="monospace" fontWeight={800}>{setup.secret}</Typography><Button size="small" startIcon={<ContentCopyRounded/>} onClick={()=>void copy(setup.otpauthUri)}>Copy authenticator URI</Button></Paper><TextField label="Current password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><TextField label="6-digit authenticator code" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} required/><Button variant="contained" onClick={enable}>Enable two-factor authentication</Button><Button onClick={()=>setSetup(null)}>Cancel setup</Button></Stack>:<Button variant="contained" onClick={startSetup}>Set up two-factor authentication</Button>}</Stack></CardContent></Card></Grid>
    <Grid size={{xs:12,lg:7}}><Card variant="outlined" sx={{borderRadius:4}}><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography variant="h6" fontWeight={900}>Active sessions</Typography><Typography color="text.secondary" fontSize={13}>Revoke access from devices you no longer recognise.</Typography></Box><Chip label={`${data.sessions.length} sessions`} /></Stack><List>{data.sessions.map((session,index)=><Box key={session.id}>{index>0&&<Divider/>}<ListItem secondaryAction={!session.current?<IconButton color="error" onClick={()=>run(()=>revokeSession(session.id),'Session revoked')}><DeleteOutlineRounded/></IconButton>:<Chip size="small" color="success" label="Current"/>}><ListItemText primary={session.device||'Unknown device'} secondary={`${session.ip||'Unknown IP'} · Last used ${session.lastUsedAt?new Date(session.lastUsedAt).toLocaleString():'Unknown'}`}/></ListItem></Box>)}</List><Divider sx={{my:2}}/><TextField fullWidth size="small" label="Password to revoke all other sessions" type="password" value={password} onChange={e=>setPassword(e.target.value)} sx={{mb:1.5}}/><Button color="warning" variant="outlined" onClick={()=>run(()=>revokeOtherSessions(password),'Other sessions revoked')}>Sign out all other devices</Button></CardContent></Card></Grid></Grid>
    <ProfessionalDialog open={passwordDialog} onClose={()=>setPasswordDialog(false)} fullWidth maxWidth="sm"><DialogTitle>Change password</DialogTitle><DialogContent dividers><Stack spacing={2}><TextField label="Current password" type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/><TextField label="New password" type="password" helperText="At least 10 characters with uppercase, lowercase and a number" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></Stack></DialogContent><DialogActions><Button onClick={()=>setPasswordDialog(false)}>Cancel</Button><Button variant="contained" onClick={async()=>{await run(()=>changePassword(currentPassword,newPassword),'Password changed and other sessions signed out');setPasswordDialog(false);setCurrentPassword('');setNewPassword('');}}>Change password</Button></DialogActions></ProfessionalDialog>
  </Box>;
}
