import { useEffect, useMemo, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Grid, LinearProgress, Stack, ToggleButton, ToggleButtonGroup, Typography } from '@mui/material';
import { ApartmentRounded, BedRounded, BusinessRounded, CheckCircleRounded, MeetingRoomRounded, StorageRounded } from '@mui/icons-material';
import { buyLandlordSubscription, cancelLandlordSubscription, getMySubscription, getSubscriptionPlans } from '../../services/api';
import { useAuth } from '../../context/AuthContext';
import { useActionDialog } from '../../components/shared/useActionDialog';

const money=(value:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value||0);
const sentence=(value:string)=>String(value||'').replaceAll('_',' ').replace(/\b\w/g,(letter)=>letter.toUpperCase());
export default function SubscriptionPage() {
  const { refreshUser } = useAuth(); const actions = useActionDialog(); const [plans,setPlans]=useState<any[]>([]); const [state,setState]=useState<any>(null); const [cycle,setCycle]=useState<'monthly'|'yearly'>('monthly'); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  async function load(){setLoading(true);setError('');try{const [p,s]=await Promise.all([getSubscriptionPlans(),getMySubscription()]);setPlans(p.data);setState(s.data);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  const sub=state?.subscription||state;
  async function buy(plan:string){try{setError('');await buyLandlordSubscription({plan,billingCycle:cycle,method:'gateway_pending'});await refreshUser();await load();}catch(e){setError((e as Error).message);}}
  async function cancel(){if(!sub?._id)return;if(!await actions.askConfirmation('Cancel the subscription? Existing property data will remain saved, but public listings will be paused after expiry.',{title:'Cancel landlord subscription',danger:true}))return;try{await cancelLandlordSubscription(sub._id);await refreshUser();await load();}catch(e){setError((e as Error).message);}}
  const usageEntries=useMemo(()=>[
    ['buildings','Buildings',BusinessRounded],['apartments','Apartments',ApartmentRounded],['rooms','Rooms',MeetingRoomRounded],['beds','Beds',BedRounded],['publicListings','Public listings',CheckCircleRounded],['storageMB','Storage MB',StorageRounded],
  ] as const,[]);
  if(loading)return <Box sx={{display:'grid',placeItems:'center',p:8}}><CircularProgress/></Box>;
  return <Box sx={{px:{xs:2,sm:3,lg:4},pb:6}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" spacing={2} sx={{mb:3}}><Box><Typography variant="h4" sx={{fontWeight:950}}>Landlord Subscription</Typography><Typography color="text.secondary">Choose limits for buildings, apartments, rooms, beds, public listings, active tenants, team members and storage.</Typography></Box><ToggleButtonGroup exclusive size="small" value={cycle} onChange={(_,value)=>value&&setCycle(value)}><ToggleButton value="monthly">Monthly</ToggleButton><ToggleButton value="yearly">Yearly</ToggleButton></ToggleButtonGroup></Stack>
  {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
  {sub&&<Card variant="outlined" sx={{borderRadius:4,mb:3}}><CardContent><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={2}><Box><Stack direction="row" gap={1} alignItems="center"><Typography variant="h6" fontWeight={900}>{sentence(sub.plan)} plan</Typography><Chip color={sub.status==='active'?'success':'warning'} label={sentence(sub.status)}/></Stack><Typography color="text.secondary" fontSize={13} mt={.5}>{sub.expiresAt?`Valid until ${new Date(sub.expiresAt).toLocaleDateString('en-IN',{dateStyle:'long'})}`:'Activation pending'}</Typography></Box>{sub.status==='active'&&<Button color="error" onClick={cancel}>Cancel renewal</Button>}</Stack>
  <Grid container spacing={1.5} mt={2}>{usageEntries.map(([key,label,Icon])=>{const used=Number(state?.usage?.[key]||0),limit=Number(state?.limits?.[key]||sub?.limits?.[key]||0),unlimited=limit>=999999;return <Grid size={{xs:12,sm:6,lg:4}} key={key}><Box sx={{p:1.7,bgcolor:'action.hover',borderRadius:3}}><Stack direction="row" justifyContent="space-between"><Stack direction="row" gap={1}><Icon fontSize="small" color="primary"/><Typography fontWeight={750} fontSize={13}>{label}</Typography></Stack><Typography fontWeight={850} fontSize={13}>{used} / {unlimited?'∞':limit}</Typography></Stack>{!unlimited&&<LinearProgress variant="determinate" value={limit?Math.min(100,used/limit*100):0} sx={{mt:1,height:6,borderRadius:9}}/>}</Box></Grid>;})}</Grid></CardContent></Card>}
  <Grid container spacing={2}>{plans.map((plan)=>{const current=sub?.status==='active'&&sub.plan===plan.key;const price=Number(plan.prices?.[cycle]||0);return <Grid size={{xs:12,md:6,xl:3}} key={plan.key}><Card variant="outlined" sx={{height:'100%',borderRadius:4,borderColor:current?'primary.main':'divider',position:'relative'}}>{plan.featured&&<Chip label="Recommended" color="primary" sx={{position:'absolute',top:14,right:14}}/>}<CardContent sx={{p:3}}><Typography variant="h6" fontWeight={950}>{plan.name}</Typography><Typography color="text.secondary" fontSize={13} minHeight={44}>{plan.description}</Typography><Typography fontSize={31} fontWeight={950} my={2}>{price?money(price):'Custom'}{price>0&&<Typography component="span" color="text.secondary" fontSize={12}>/{cycle==='monthly'?'mo':'yr'}</Typography>}</Typography><Stack spacing={1.1} mb={3}>{[['Buildings',plan.limits?.buildings],['Apartments',plan.limits?.apartments],['Rooms',plan.limits?.rooms],['Beds',plan.limits?.beds],['Public listings',plan.limits?.publicListings],['Active tenants',plan.limits?.activeTenants],['Team members',plan.limits?.teamMembers],['Storage',`${Math.round(Number(plan.limits?.storageMB||0)/1024)} GB`]].map(([label,value])=><Stack key={String(label)} direction="row" justifyContent="space-between"><Typography color="text.secondary" fontSize={12}>{label}</Typography><Typography fontWeight={800} fontSize={12}>{Number(value)>=999999?'Unlimited':value}</Typography></Stack>)}</Stack><Stack direction="row" gap={.7} flexWrap="wrap" mb={3}>{Object.entries(plan.features||{}).filter(([,enabled])=>enabled).map(([feature])=><Chip key={feature} size="small" label={sentence(feature)} variant="outlined"/>)}</Stack><Button fullWidth variant={current?'outlined':'contained'} disabled={current||plan.key==='enterprise'} onClick={()=>buy(plan.key)}>{current?'Current plan':plan.key==='enterprise'?'Contact sales':'Choose plan'}</Button></CardContent></Card></Grid>;})}</Grid>
  {actions.dialogs}<Alert severity="info" sx={{mt:3}}>When a plan expires or its limits are reduced, existing buildings, apartments, rooms, beds, tenants and documents remain saved. New additions and public publishing are restricted until the account upgrades or returns within the plan limits.</Alert></Box>;
}
