import { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, DialogActions, DialogContent, DialogTitle, FormControlLabel, Grid, LinearProgress, Radio, RadioGroup, Snackbar, Stack, Switch, Typography } from '@mui/material';
import ProfessionalDialog from '../../components/shared/ProfessionalDialog';
import { CheckCircleRounded, WorkspacePremiumRounded } from '@mui/icons-material';
import { buySurveyorSubscription, cancelSurveyorSubscription, changeSurveyorPlan, getMySurveyorSubscription, getSurveyorPlans, renewSurveyorSubscription, switchAccountMode } from '../../services/api';
import { useAuth } from '../../context/AuthContext';
import { useActionDialog } from '../../components/shared/useActionDialog';

const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0);
const title = (value: string) => String(value || '').replaceAll('_', ' ').replace(/\b\w/g, (m) => m.toUpperCase());

export default function SurveyorSubscriptionPage() {
  const { refreshUser } = useAuth();
  const actions = useActionDialog();
  const [plans, setPlans] = useState<any[]>([]); const [state, setState] = useState<any>(null);
  const [cycle, setCycle] = useState<'monthly' | 'yearly'>('monthly'); const [autoRenew, setAutoRenew] = useState(true);
  const [selected, setSelected] = useState<any>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  async function load() { setLoading(true); setError(''); try { const [p, s] = await Promise.all([getSurveyorPlans(), getMySurveyorSubscription()]); setPlans(p.data); setState(s.data); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function purchase() { if (!selected) return; setBusy(true); try { const result = await buySurveyorSubscription({ plan: selected.key, billingCycle: cycle, autoRenew }); await refreshUser(); setSelected(null); setNotice(result.message || 'Payment request submitted for verification'); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function change(plan: any) { setBusy(true); try { const result = await changeSurveyorPlan(plan.key); setNotice(result.message || `Plan change requested for ${plan.name}`); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function renew() { setBusy(true); try { const result = await renewSurveyorSubscription({ autoRenew }); await refreshUser(); setNotice(result.message || 'Renewal payment submitted for verification'); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function cancel(immediate = false) { const id = state?.subscription?._id; if (!id || !await actions.askConfirmation(immediate ? 'Cancel immediately and pause public listings?' : 'Turn off renewal at the end of this billing period?', { title: immediate ? 'Cancel surveyor subscription' : 'Stop automatic renewal', danger: immediate })) return; setBusy(true); try { await cancelSurveyorSubscription(id, immediate); await refreshUser(); setNotice('Subscription updated'); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function enterMode() { setBusy(true); try { await switchAccountMode('surveyor'); await refreshUser(); window.location.href = '/app/surveyor-dashboard'; } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (loading) return <Box sx={{ p: 8, display: 'grid', placeItems: 'center' }}><CircularProgress /></Box>;
  const sub = state?.subscription; const usage = state?.usage;
  return <Box sx={{ px: { xs: 2, sm: 3, lg: 4 }, pb: 6 }}>
    <Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ md: 'center' }} spacing={2} sx={{ mb: 3 }}><Box><Typography variant="h4" sx={{ fontWeight: 900, letterSpacing: '-.04em' }}>Surveyor Subscription</Typography><Typography color="text.secondary">Activate professional survey services from this same Tenant account.</Typography></Box>{state?.enabled && <Button variant="contained" startIcon={<WorkspacePremiumRounded />} onClick={enterMode} disabled={busy}>Enter Surveyor Mode</Button>}</Stack>
    {error && <Alert severity="error" onClose={() => setError('')} sx={{ mb: 2 }}>{error}</Alert>}
    {sub && <Card elevation={0} sx={{ mb: 3, border: '1px solid', borderColor: 'divider', borderRadius: 5, overflow: 'hidden' }}><CardContent sx={{ p: 3 }}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" spacing={3}><Box><Stack direction="row" spacing={1} alignItems="center"><Typography variant="h5" sx={{ fontWeight: 900 }}>{sub.plan?.name || title(sub.planKey)}</Typography><Chip label={title(sub.status)} color={['active','trial','expiring_soon','grace_period'].includes(sub.status) ? 'success' : 'warning'} /></Stack><Typography color="text.secondary" sx={{ mt: 1 }}>Valid until {sub.expiresAt ? new Date(sub.expiresAt).toLocaleDateString('en-IN', { dateStyle: 'long' }) : '—'} · {title(sub.billingCycle)} billing</Typography><Typography color="text.secondary" sx={{ fontSize: 13 }}>Auto-renewal: {sub.autoRenew ? 'On' : 'Off'}</Typography></Box><Stack direction="row" spacing={1} flexWrap="wrap"><Button variant="outlined" onClick={renew} disabled={busy}>Renew</Button><Button variant="outlined" color="warning" onClick={() => cancel(false)} disabled={busy}>Stop renewal</Button><Button variant="text" color="error" onClick={() => cancel(true)} disabled={busy}>Cancel now</Button></Stack></Stack>
      {usage && <Grid container spacing={2} sx={{ mt: 1 }}>{Object.entries(usage.limits || {}).map(([key, rawLimit]: any) => { const usageKey = key === 'jobsPerMonth' ? 'jobs' : key === 'quotationsPerMonth' ? 'quotations' : key === 'reportsPerMonth' ? 'reports' : key === 'storageMb' ? 'storageBytes' : key; const limit = key === 'storageMb' ? Number(rawLimit || 0) * 1024 * 1024 : Number(rawLimit || 0); const used = Number(usage.used?.[usageKey] || 0); const percent = limit < 0 ? 0 : Math.min(100, limit ? used / limit * 100 : 100); const shownUsed = key === 'storageMb' ? `${Math.round(used / 1024 / 1024)} MB` : used; const shownLimit = key === 'storageMb' ? `${rawLimit} MB` : limit < 0 ? 'Unlimited' : limit; return <Grid size={{ xs: 12, sm: 6, md: 4 }} key={key}><Box sx={{ p: 2, bgcolor: 'action.hover', borderRadius: 3 }}><Stack direction="row" justifyContent="space-between"><Typography sx={{ fontWeight: 750, fontSize: 13 }}>{title(key)}</Typography><Typography sx={{ fontSize: 12 }}>{shownUsed} / {shownLimit}</Typography></Stack><LinearProgress variant="determinate" value={percent} sx={{ mt: 1, height: 7, borderRadius: 99 }} /></Box></Grid>; })}</Grid>}
    </CardContent></Card>}
    <Stack direction="row" justifyContent="center" sx={{ mb: 3 }}><RadioGroup row value={cycle} onChange={(e) => setCycle(e.target.value as any)}><FormControlLabel value="monthly" control={<Radio />} label="Monthly" /><FormControlLabel value="yearly" control={<Radio />} label="Yearly — better value" /></RadioGroup></Stack>
    <Grid container spacing={2.2}>{plans.map((plan) => { const current = sub?.planKey === plan.key; const price = plan.prices?.[cycle] || 0; return <Grid size={{ xs: 12, md: 6, lg: 4 }} key={plan.key}><Card elevation={0} sx={{ height: '100%', border: '1px solid', borderColor: current ? 'primary.main' : 'divider', borderRadius: 5, position: 'relative' }}>{current && <Chip label="Current plan" color="primary" size="small" sx={{ position: 'absolute', top: 16, right: 16 }} />}<CardContent sx={{ p: 3 }}><Typography variant="h6" sx={{ fontWeight: 900 }}>{plan.name}</Typography><Typography color="text.secondary" sx={{ minHeight: 44, fontSize: 13 }}>{plan.description}</Typography><Typography sx={{ fontWeight: 950, fontSize: 32, mt: 2 }}>{money(price)}<Typography component="span" color="text.secondary" sx={{ fontSize: 12, fontWeight: 500 }}>/{cycle === 'monthly' ? 'month' : 'year'}</Typography></Typography><Stack spacing={1.1} sx={{ my: 2.5 }}>{[
          `${plan.limits?.publicServices ?? 0} public services`, `${plan.limits?.jobsPerMonth ?? 0} jobs/month`, `${plan.limits?.quotationsPerMonth ?? 0} quotations/month`, `${plan.limits?.teamMembers ?? 0} team members`, `${plan.limits?.reportsPerMonth ?? 0} reports/month`, `${plan.limits?.storageMb ?? 0} MB storage`, plan.features?.advancedMapping ? 'Advanced mapping & GIS' : 'Standard mapping', plan.features?.analytics ? 'Professional analytics' : 'Basic analytics', `${title(plan.supportLevel)} support`,
        ].map((line) => <Stack direction="row" spacing={1} key={line}><CheckCircleRounded color="success" sx={{ fontSize: 18 }} /><Typography sx={{ fontSize: 13 }}>{line}</Typography></Stack>)}</Stack><Button fullWidth variant={current ? 'outlined' : 'contained'} disabled={busy || current} onClick={() => sub ? change(plan) : setSelected(plan)}>{current ? 'Active' : sub ? 'Change plan' : 'Choose plan'}</Button></CardContent></Card></Grid>; })}</Grid>
    <ProfessionalDialog open={Boolean(selected)} onClose={() => setSelected(null)} fullWidth maxWidth="sm" PaperProps={{ sx: { borderRadius: 4 } }}><DialogTitle sx={{ fontWeight: 900 }}>Activate {selected?.name}</DialogTitle><DialogContent><Typography color="text.secondary">A payment request will be created. Surveyor Mode is enabled only after the payment is verified by the configured payment gateway or an authorised administrator.</Typography><FormControlLabel sx={{ mt: 2 }} control={<Switch checked={autoRenew} onChange={(e) => setAutoRenew(e.target.checked)} />} label="Enable automatic renewal" /></DialogContent><DialogActions><Button onClick={() => setSelected(null)}>Cancel</Button><Button variant="contained" onClick={purchase} disabled={busy}>{busy ? 'Submitting…' : `Submit ${money(selected?.prices?.[cycle] || 0)} payment request`}</Button></DialogActions></ProfessionalDialog>
    {actions.dialogs}
    <Snackbar open={Boolean(notice)} autoHideDuration={3500} onClose={() => setNotice('')} message={notice} />
  </Box>;
}
