import { useEffect, useState, type FormEvent } from 'react';
import { Alert, Avatar, Box, Button, Chip, CircularProgress, Grid, MenuItem, Paper, Snackbar, Stack, TextField, Typography } from '@mui/material';
import { FactCheckRounded, PhotoCameraRounded, SaveRounded, SendRounded } from '@mui/icons-material';
import { getSurveyorVerification, saveSurveyorVerification, submitSurveyorVerification, uploadSiteAsset } from '../../services/api';
import { useActionDialog } from '../../components/shared/useActionDialog';
import LocationFields from '../../components/shared/LocationFields';

const fields = [
 ['legalName','Full legal name'],['phone','Phone number'],['email','Email address'],['address.line1','Residential or office address'],['address.postalCode','Postal code'],['registrationNumber','Surveyor registration number'],['licenceNumber','Professional licence number'],['licenceAuthority','Licence issuing authority'],['licenceIssueDate','Licence issue date','date'],['licenceExpiryDate','Licence expiry date','date'],['yearsExperience','Years of experience','number'],['taxRegistration','Tax registration details'],['businessRegistrationNumber','Business registration certificate number'],['agencyRegistrationNumber','Agency registration number'],['insurance.provider','Insurance provider'],['insurance.policyNumber','Insurance policy number'],['insurance.expiresAt','Insurance expiry','date'],['bankVerification.accountName','Bank account name'],['bankVerification.maskedAccount','Masked account number'],['bankVerification.ifsc','IFSC code'],
] as const;
function get(obj:any,path:string){return path.split('.').reduce((v,k)=>v?.[k],obj)} function set(obj:any,path:string,value:any){const copy=structuredClone(obj); const keys=path.split('.'); let cur=copy; keys.slice(0,-1).forEach(k=>{cur[k]||={};cur=cur[k]});cur[keys.at(-1)!]=value;return copy}
export default function SurveyorVerificationPage(){
 const actions=useActionDialog();
 const [form,setForm]=useState<any>({qualifications:'',certifications:'',serviceAreas:''}); const [avatarFile,setAvatarFile]=useState<File|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
 async function load(){setLoading(true);try{const r=await getSurveyorVerification();const v=r.data||{};setForm({...v,qualifications:(v.qualifications||[]).join(', '),certifications:(v.certifications||[]).join(', '),serviceAreas:(v.serviceAreas||[]).map((x:any)=>x.name).join(', ')});}catch(e){setError((e as Error).message)}finally{setLoading(false)}} useEffect(()=>{load()},[]);
 async function profilePhoto(){if(!avatarFile)return form.profilePhoto;return (await uploadSiteAsset(avatarFile)).data.url;}
 function payload(){return {...form,qualifications:String(form.qualifications||'').split(',').map((x)=>x.trim()).filter(Boolean),certifications:String(form.certifications||'').split(',').map((x)=>x.trim()).filter(Boolean),serviceAreas:String(form.serviceAreas||'').split(',').map((name)=>({name:name.trim(),radiusKm:50})).filter((x)=>x.name)};}
 async function save(e?:FormEvent){e?.preventDefault();setBusy(true);try{const data=payload();data.profilePhoto=await profilePhoto();await saveSurveyorVerification(data);setAvatarFile(null);setNotice('Verification draft saved');await load()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 async function submit(){if(!await actions.askConfirmation('Submit verification for administrator review?', {title:'Submit professional verification'}))return;setBusy(true);try{const data=payload();data.profilePhoto=await profilePhoto();await saveSurveyorVerification(data);setAvatarFile(null);await submitSurveyorVerification();setNotice('Verification submitted');await load()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 if(loading)return <Box sx={{p:10,display:'grid',placeItems:'center'}}><CircularProgress/></Box>;
 return <Box sx={{px:{xs:2,sm:3,lg:4},pb:6}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" spacing={2} sx={{mb:3}}><Box><Typography variant="h4" sx={{fontWeight:950,letterSpacing:'-.04em'}}>Professional Verification</Typography><Typography color="text.secondary">Verification is required before your profile and services can be published.</Typography></Box><Chip icon={<FactCheckRounded/>} label={String(form.status||'not submitted').replaceAll('_',' ')} color={form.status==='verified'?'success':form.status==='rejected'?'error':'warning'} sx={{textTransform:'capitalize'}}/></Stack>{error&&<Alert severity="error" onClose={()=>setError('')} sx={{mb:2}}>{error}</Alert>}{form.reviewerNotes&&<Alert severity="info" sx={{mb:2}}>Reviewer note: {form.reviewerNotes}</Alert>}{form.rejectionReason&&<Alert severity="error" sx={{mb:2}}>Reason: {form.rejectionReason}</Alert>}
 <Paper component="form" onSubmit={save} elevation={0} sx={{p:{xs:2,md:3},border:'1px solid',borderColor:'divider',borderRadius:5}}><Grid container spacing={2}><Grid size={{xs:12}}><Stack direction={{xs:'column',sm:'row'}} spacing={2} alignItems={{sm:'center'}}><Avatar src={avatarFile?URL.createObjectURL(avatarFile):form.profilePhoto} sx={{width:88,height:88}}/><Button component="label" variant="outlined" startIcon={<PhotoCameraRounded/>}>Upload profile photograph<input hidden type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(event)=>setAvatarFile(event.target.files?.[0]||null)}/></Button></Stack></Grid><Grid size={{xs:12}}><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(3,1fr)'},gap:2}}><LocationFields value={{country:get(form,'address.country'),state:get(form,'address.state'),city:get(form,'address.city')}} onChange={(next)=>setForm((old:any)=>set(set(set(old,'address.country',next.country||''),'address.state',next.state||''),'address.city',next.city||''))}/></Box></Grid>{fields.map(([name,label,type])=><Grid size={{ xs: 12, md: 6 }} key={name}><TextField fullWidth size="small" label={label} type={type||'text'} value={get(form,name)||''} onChange={(e)=>setForm((old:any)=>set(old,name,type==='number'?Number(e.target.value):e.target.value))} InputLabelProps={type==='date'?{shrink:true}:undefined}/></Grid>)}<Grid size={{ xs: 12, md: 6 }}><TextField fullWidth size="small" label="Qualifications (comma separated)" value={form.qualifications||''} onChange={(e)=>setForm({...form,qualifications:e.target.value})}/></Grid><Grid size={{ xs: 12, md: 6 }}><TextField fullWidth size="small" label="Certifications (comma separated)" value={form.certifications||''} onChange={(e)=>setForm({...form,certifications:e.target.value})}/></Grid><Grid size={12}><TextField fullWidth size="small" label="Service areas (comma separated)" value={form.serviceAreas||''} onChange={(e)=>setForm({...form,serviceAreas:e.target.value})}/></Grid><Grid size={{ xs: 12, md: 6 }}><TextField select fullWidth size="small" label="Bank verification status" value={get(form,'bankVerification.status')||'pending'} onChange={(e)=>setForm((old:any)=>set(old,'bankVerification.status',e.target.value))}><MenuItem value="pending">Pending</MenuItem><MenuItem value="verified">Verified</MenuItem></TextField></Grid></Grid><Stack direction="row" justifyContent="flex-end" spacing={1} sx={{mt:3}}><Button type="submit" variant="outlined" startIcon={<SaveRounded/>} disabled={busy||['submitted','under_review','verified'].includes(form.status)}>Save draft</Button><Button variant="contained" startIcon={<SendRounded/>} onClick={submit} disabled={busy||['submitted','under_review','verified'].includes(form.status)}>Submit for review</Button></Stack></Paper>{actions.dialogs}<Snackbar open={Boolean(notice)} autoHideDuration={3500} onClose={()=>setNotice('')} message={notice}/></Box>;
}
