import { useEffect, useState, type FormEvent } from 'react';
import { Alert, Box, Button, Chip, CircularProgress, Grid, MenuItem, Paper, Snackbar, Stack, TextField, Typography } from '@mui/material';
import { ContentCopyRounded, LinkOffRounded, PublicRounded, SaveRounded, VisibilityOffRounded } from '@mui/icons-material';
import { createSurveyorPrivateLink, getMySurveyorSubscription, revokeSurveyorPrivateLink, saveSurveyorProfile, setSurveyorProfileVisibility } from '../../services/api';
import { useActionDialog } from '../../components/shared/useActionDialog';
const array=(v:any)=>Array.isArray(v)?v.join(', '):v||''; const split=(v:any)=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
export default function SurveyorProfilePage(){const actions=useActionDialog();const [form,setForm]=useState<any>({profileType:'individual',availability:'available',specialisations:'',languages:'',qualifications:'',certifications:'',equipmentSummary:'',serviceLocations:''});const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[share,setShare]=useState('');
 async function load(){setLoading(true);try{const r=await getMySurveyorSubscription();const p=r.data?.profile||{};setForm({...p,profileType:p.profileType||'individual',availability:p.availability||'available',specialisations:array(p.specialisations),languages:array(p.languages),qualifications:array(p.qualifications),certifications:array(p.certifications),equipmentSummary:array(p.equipmentSummary),serviceLocations:(p.serviceLocations||[]).map((x:any)=>[x.city,x.state].filter(Boolean).join(', ')).join('; ')});}catch(e){setError((e as Error).message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 function body(){return {...form,yearsExperience:Number(form.yearsExperience||0),teamSize:Number(form.teamSize||0),startingPrice:Number(form.startingPrice||0),averageCompletionDays:Number(form.averageCompletionDays||0),specialisations:split(form.specialisations),languages:split(form.languages),qualifications:split(form.qualifications),certifications:split(form.certifications),equipmentSummary:split(form.equipmentSummary),serviceLocations:String(form.serviceLocations||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const[c,s]=x.split(',').map(y=>y.trim());return{city:c,state:s,radiusKm:50}})};}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);try{await saveSurveyorProfile(body());setNotice('Professional profile saved');await load()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 async function visibility(next:'private'|'public'){setBusy(true);try{await saveSurveyorProfile(body());await setSurveyorProfileVisibility(next);setNotice(next==='public'?'Profile submitted/published for marketplace':'Profile made private');await load()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 async function link(){const entered=await actions.askText('Optional access code for this private link. Leave it blank for no access code.',{title:'Create private profile link',label:'Access code'});if(entered===null)return;const accessCode=entered.trim()||undefined;setBusy(true);try{const r=await createSurveyorPrivateLink(accessCode);const url=new URL(r.data.url,window.location.origin).toString();setShare(url);await navigator.clipboard?.writeText(url);setNotice(accessCode?'Private link created with access-code protection and copied':'Private link created and copied')}catch(err){setError((err as Error).message)}finally{setBusy(false)}} async function revoke(){setBusy(true);try{await revokeSurveyorPrivateLink();setShare('');setNotice('Private link revoked')}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 if(loading)return <Box sx={{p:10,display:'grid',placeItems:'center'}}><CircularProgress/></Box>;
 return <Box sx={{px:{xs:2,sm:3,lg:4},pb:6}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" spacing={2} sx={{mb:3}}><Box><Typography variant="h4" sx={{fontWeight:950,letterSpacing:'-.04em'}}>Professional Profile</Typography><Typography color="text.secondary">Your public profile appears in the Surveyor Marketplace after verification.</Typography></Box><Stack direction="row" spacing={1}><Chip label={form.verificationStatus||'not verified'} color={form.verificationStatus==='verified'?'success':'warning'}/><Chip label={`${form.visibility||'private'} · ${form.publicationStatus||'draft'}`}/></Stack></Stack>{error&&<Alert severity="error" onClose={()=>setError('')} sx={{mb:2}}>{error}</Alert>}{share&&<Alert severity="success" sx={{mb:2}} action={<Button size="small" onClick={()=>navigator.clipboard.writeText(share)}>Copy</Button>}>{share}</Alert>}
 <Paper component="form" onSubmit={save} elevation={0} sx={{p:{xs:2,md:3},border:'1px solid',borderColor:'divider',borderRadius:5}}><Grid container spacing={2}><Grid size={{ xs: 12, md: 6 }}><TextField select fullWidth size="small" label="Profile type" value={form.profileType} onChange={(e)=>setForm({...form,profileType:e.target.value})}><MenuItem value="individual">Independent surveyor</MenuItem><MenuItem value="agency">Survey agency</MenuItem></TextField></Grid><Grid size={{ xs: 12, md: 6 }}><TextField select fullWidth size="small" label="Availability" value={form.availability} onChange={(e)=>setForm({...form,availability:e.target.value})}>{['available','busy','limited','unavailable'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Grid>{[
 ['name','Surveyor or agency name'],['professionalTitle','Professional title'],['profilePhoto','Profile photograph URL'],['agencyLogo','Agency logo URL'],['yearsExperience','Years of experience','number'],['registrationNumber','Registration number'],['licenceNumber','Licence number'],['teamSize','Team size','number'],['startingPrice','Starting service price','number'],['averageCompletionDays','Average completion time (days)','number'],['publicContact.phone','Public phone'],['publicContact.email','Public email'],['publicContact.website','Website'],['officeAddress.line1','Office address'],['officeAddress.city','City'],['officeAddress.state','State'],['officeAddress.postalCode','Postal code'],
 ].map(([name,label,type])=>{const get=(o:any,p:string)=>p.split('.').reduce((v,k)=>v?.[k],o);const update=(p:string,v:any)=>setForm((old:any)=>{const copy=structuredClone(old);const ks=p.split('.');let c=copy;ks.slice(0,-1).forEach(k=>{c[k]||={};c=c[k]});c[ks.at(-1)!]=v;return copy});return <Grid size={{ xs: 12, md: 6 }} key={name}><TextField fullWidth size="small" label={label} type={type||'text'} value={get(form,name)||''} onChange={(e)=>update(name,type==='number'?Number(e.target.value):e.target.value)}/></Grid>})}<Grid size={12}><TextField multiline rows={4} fullWidth size="small" label="Business description" value={form.description||''} onChange={(e)=>setForm({...form,description:e.target.value})}/></Grid>{[['specialisations','Specialisations'],['languages','Languages spoken'],['qualifications','Qualifications'],['certifications','Certifications'],['equipmentSummary','Equipment used']].map(([name,label])=><Grid size={{ xs: 12, md: 6 }} key={name}><TextField fullWidth size="small" label={`${label} (comma separated)`} value={form[name]||''} onChange={(e)=>setForm({...form,[name]:e.target.value})}/></Grid>)}<Grid size={12}><TextField fullWidth size="small" label="Service locations (City, State; City, State)" value={form.serviceLocations||''} onChange={(e)=>setForm({...form,serviceLocations:e.target.value})}/></Grid><Grid size={12}><TextField multiline rows={3} fullWidth size="small" label="Terms and conditions" value={form.terms||''} onChange={(e)=>setForm({...form,terms:e.target.value})}/></Grid></Grid><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" spacing={1} sx={{mt:3}}><Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<ContentCopyRounded/>} onClick={link} disabled={busy}>Private link</Button><Button variant="text" color="warning" startIcon={<LinkOffRounded/>} onClick={revoke} disabled={busy}>Revoke</Button></Stack><Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<VisibilityOffRounded/>} onClick={()=>visibility('private')} disabled={busy}>Make private</Button><Button variant="outlined" startIcon={<PublicRounded/>} onClick={()=>visibility('public')} disabled={busy}>Publish</Button><Button type="submit" variant="contained" startIcon={<SaveRounded/>} disabled={busy}>Save</Button></Stack></Stack></Paper>{actions.dialogs}<Snackbar open={Boolean(notice)} autoHideDuration={3500} onClose={()=>setNotice('')} message={notice}/></Box>}
