import { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Grid, LinearProgress, Paper, Stack, Typography } from '@mui/material';
import { AssignmentRounded, CalendarMonthRounded, DescriptionRounded, EngineeringRounded, ExploreRounded, PaymentsRounded, RequestQuoteRounded, StarRounded, StorefrontRounded, TrendingUpRounded } from '@mui/icons-material';
import { useNavigate } from 'react-router';
import { getSurveyorDashboard } from '../../services/api';

const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0);
const sum = (obj: Record<string, number> = {}) => Object.values(obj).reduce((a, b) => a + Number(b || 0), 0);
function Kpi({ label, value, icon: Icon, onClick }: any) { return <Card onClick={onClick} elevation={0} sx={{ border: '1px solid', borderColor: 'divider', borderRadius: 4, cursor: onClick ? 'pointer' : 'default', height: '100%' }}><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography color="text.secondary" sx={{ fontSize: 12, fontWeight: 700 }}>{label}</Typography><Typography sx={{ fontWeight: 950, fontSize: 27, mt: .5 }}>{value}</Typography></Box><Box sx={{ width: 44, height: 44, borderRadius: 3, bgcolor: 'primary.main', color: 'primary.contrastText', display: 'grid', placeItems: 'center' }}><Icon /></Box></Stack></CardContent></Card>; }
export default function SurveyorDashboardPage() {
 const navigate = useNavigate(); const [data, setData] = useState<any>(); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
 useEffect(() => { getSurveyorDashboard().then((r) => setData(r.data)).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []);
 if (loading) return <Box sx={{ p: 10, display: 'grid', placeItems: 'center' }}><CircularProgress /></Box>;
 const usage = data?.usage || {}; const projectValue = Object.values(data?.projects || {}).reduce((a: number, b: any) => a + Number(b || 0), 0);
 const paid = (data?.finances || []).reduce((a: number, r: any) => a + Number(r.paid || 0), 0); const outstanding = (data?.finances || []).reduce((a: number, r: any) => a + Math.max(0, Number(r.total || 0) - Number(r.paid || 0)), 0);
 return <Box sx={{ px: { xs: 2, sm: 3, lg: 4 }, pb: 6 }}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ md: 'center' }} spacing={2} sx={{ mb: 3 }}><Box><Typography variant="h4" sx={{ fontWeight: 950, letterSpacing: '-.04em' }}>Surveyor Workspace</Typography><Typography color="text.secondary">Manage enquiries, quotations, fieldwork, reports and professional growth.</Typography></Box><Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<ExploreRounded />} onClick={() => navigate('/app/survey-job-marketplace')}>Find jobs</Button><Button variant="contained" startIcon={<StorefrontRounded />} onClick={() => navigate('/app/survey-services?new=1')}>Add service</Button></Stack></Stack>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
 <Paper elevation={0} sx={{ p: 2.5, mb: 2.5, border: '1px solid', borderColor: 'divider', borderRadius: 4 }}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" spacing={2}><Box><Stack direction="row" spacing={1} alignItems="center"><Typography sx={{ fontWeight: 900 }}>{data?.subscription?.plan?.name || data?.subscription?.planKey || 'Surveyor plan'}</Typography><Chip size="small" color="success" label={String(data?.subscription?.status || 'active').replaceAll('_',' ')} /></Stack><Typography color="text.secondary" sx={{ fontSize: 12, mt: .5 }}>Expires {data?.subscription?.expiresAt ? new Date(data.subscription.expiresAt).toLocaleDateString('en-IN') : '—'}</Typography></Box><Button onClick={() => navigate('/app/surveyor-subscription')}>Manage subscription</Button></Stack><Grid container spacing={2} sx={{ mt: .5 }}>{[['jobs','jobsPerMonth'],['quotations','quotationsPerMonth'],['reports','reportsPerMonth'],['publicServices','publicServices']].map(([key, limitKey]) => { const limit = Number(usage.limits?.[limitKey] || 0), used = Number(usage.used?.[key] || 0); return <Grid size={{ xs: 12, sm: 6, md: 3 }} key={key}><Typography sx={{ fontSize: 12, fontWeight: 750, textTransform: 'capitalize' }}>{key.replace(/([A-Z])/g,' $1')}</Typography><Stack direction="row" justifyContent="space-between"><Typography color="text.secondary" sx={{ fontSize: 11 }}>{used} used</Typography><Typography color="text.secondary" sx={{ fontSize: 11 }}>{limit < 0 ? 'Unlimited' : `${Math.max(0, limit-used)} left`}</Typography></Stack><LinearProgress variant="determinate" value={limit < 0 ? 0 : Math.min(100, limit ? used/limit*100 : 100)} sx={{ mt: .7, height: 6, borderRadius: 99 }} /></Grid>; })}</Grid></Paper>
 <Grid container spacing={2}>{[
  ['Public services', data?.services?.published || 0, StorefrontRounded, '/app/survey-services'], ['Job invitations', data?.jobInvitations || 0, AssignmentRounded, '/app/survey-job-marketplace'], ['Quotations', sum(data?.quotations), RequestQuoteRounded, '/app/survey-quotations'], ['Active projects', projectValue, EngineeringRounded, '/app/survey-projects'], ['Upcoming visits', data?.upcomingVisits || 0, CalendarMonthRounded, '/app/site-visits'], ['Reports', sum(data?.reports), DescriptionRounded, '/app/survey-reports'], ['Total received', money(paid), PaymentsRounded, '/app/payments'], ['Outstanding', money(outstanding), TrendingUpRounded, '/app/payments'], ['Average rating', `${Number(data?.reviews?.average || 0).toFixed(1)} / 5`, StarRounded, '/app/survey-reviews'],
 ].map(([label,value,Icon,path]: any) => <Grid size={{ xs: 12, sm: 6, md: 4, lg: 3 }} key={label}><Kpi label={label} value={value} icon={Icon} onClick={() => navigate(path)} /></Grid>)}</Grid>
 <Grid container spacing={2.5} sx={{ mt: .5 }}><Grid size={{ xs: 12, lg: 7 }}><Paper elevation={0} sx={{ p: 3, borderRadius: 4, border: '1px solid', borderColor: 'divider' }}><Typography sx={{ fontWeight: 900, mb: 2 }}>Project pipeline</Typography><Stack spacing={1.3}>{Object.entries(data?.projects || {}).map(([status,count]: any) => <Stack key={status} direction="row" alignItems="center" spacing={1.5}><Typography sx={{ width: 165, fontSize: 12, textTransform: 'capitalize' }}>{status.replaceAll('_',' ')}</Typography><LinearProgress variant="determinate" value={Math.min(100, Number(count) * 14)} sx={{ flex: 1, height: 8, borderRadius: 99 }} /><Typography sx={{ fontWeight: 850, minWidth: 24 }}>{count}</Typography></Stack>)}{!Object.keys(data?.projects || {}).length && <Typography color="text.secondary">No projects yet.</Typography>}</Stack></Paper></Grid><Grid size={{ xs: 12, lg: 5 }}><Paper elevation={0} sx={{ p: 3, borderRadius: 4, border: '1px solid', borderColor: 'divider', height: '100%' }}><Typography sx={{ fontWeight: 900 }}>Marketplace performance</Typography><Stack spacing={2.2} sx={{ mt: 2.5 }}><Stack direction="row" justifyContent="space-between"><Typography color="text.secondary">Profile views</Typography><Typography sx={{ fontWeight: 900 }}>{data?.profile?.metrics?.views || 0}</Typography></Stack><Stack direction="row" justifyContent="space-between"><Typography color="text.secondary">Enquiries</Typography><Typography sx={{ fontWeight: 900 }}>{data?.profile?.metrics?.enquiries || 0}</Typography></Stack><Stack direction="row" justifyContent="space-between"><Typography color="text.secondary">Completed projects</Typography><Typography sx={{ fontWeight: 900 }}>{data?.profile?.completedProjects || 0}</Typography></Stack><Stack direction="row" justifyContent="space-between"><Typography color="text.secondary">Availability</Typography><Chip size="small" label={data?.profile?.availability || 'not configured'} /></Stack></Stack><Button fullWidth variant="outlined" sx={{ mt: 3 }} onClick={() => navigate('/app/surveyor-profile')}>Edit professional profile</Button></Paper></Grid></Grid>
 </Box>;
}
