import { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Grid, LinearProgress, Stack, TextField, Typography } from '@mui/material';
import { SaveRounded, VerifiedUserRounded } from '@mui/icons-material';
import { getResource, submitTenantKyc } from '../../services/api';
import { useAuth } from '../../context/AuthContext';

export default function TenantKycPage(){
  const {user,refreshUser}=useAuth();const [form,setForm]=useState<Record<string,string>>({governmentId:'',addressProof:'',profilePhoto:'',selfiePhoto:'',employmentProof:''});const [record,setRecord]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  async function load(){try{const result=await getResource('tenant-kyc',{limit:10});const own=result.data.find((item:any)=>String(item.user?._id||item.user)===user?._id)||result.data[0];if(own){setRecord(own);setForm((old)=>({...old,governmentId:own.governmentId||'',addressProof:own.addressProof||'',profilePhoto:own.profilePhoto||'',selfiePhoto:own.selfiePhoto||'',employmentProof:own.employmentProof||''}));}}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  async function submit(){setError('');try{const result=await submitTenantKyc(form);setRecord(result.data);setNotice('KYC submitted for review');await refreshUser();}catch(e){setError((e as Error).message);}}
  const status=String(record?.status||user?.kycStatus||'not_started');const progressByStatus:Record<string,number>={not_started:10,incomplete:25,submitted:55,under_review:70,changes_required:45,verified:100,rejected:35,expired:30,suspended:20,pending:55};const progress=progressByStatus[status]||10;
  if(loading)return <Box sx={{py:16,display:'grid',placeItems:'center'}}><CircularProgress/></Box>;
  return <Box sx={{px:{xs:2,sm:3,lg:4},pb:6,maxWidth:1000}}><Stack direction="row" alignItems="center" spacing={1.5} mb={1}><VerifiedUserRounded color="primary"/><Typography variant="h4" fontWeight={950}>Tenant KYC Verification</Typography></Stack><Typography color="text.secondary" mb={3}>Complete verification to apply for properties, schedule visits, sign agreements and manage tenancy.</Typography>
  {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{notice&&<Alert severity="success" sx={{mb:2}}>{notice}</Alert>}{record?.reason&&<Alert severity={status==='verified'?'success':'warning'} sx={{mb:2}}>{record.reason}</Alert>}
  <Card variant="outlined" sx={{borderRadius:4,mb:3}}><CardContent><Stack direction="row" justifyContent="space-between" mb={1}><Typography fontWeight={850}>Verification progress</Typography><Chip label={String(status).replaceAll('_',' ')} color={status==='verified'?'success':status==='rejected'?'error':'warning'}/></Stack><LinearProgress variant="determinate" value={progress} sx={{height:9,borderRadius:9}}/><Typography color="text.secondary" fontSize={12} mt={1}>{status==='verified'?'Your full tenant dashboard access is active.':'Public browsing remains available; applications require verified KYC.'}</Typography></CardContent></Card>
  <Card variant="outlined" sx={{borderRadius:4}}><CardContent><Typography variant="h6" fontWeight={900} mb={.5}>Verification documents</Typography><Typography color="text.secondary" fontSize={13} mb={3}>Use secure Document Vault file IDs or approved image URLs. Documents remain private and ownership-scoped.</Typography><Grid container spacing={2}>{[
    ['governmentId','Government identity document ID'],['addressProof','Address proof document ID'],['profilePhoto','Profile photograph URL'],['selfiePhoto','Selfie verification URL'],['employmentProof','Employment or student proof ID'],
  ].map(([key,label])=><Grid size={{xs:12,md:6}} key={key}><TextField fullWidth label={label} value={form[key]||''} onChange={(event)=>setForm((old)=>({...old,[key]:event.target.value}))} required={['governmentId','addressProof','profilePhoto'].includes(key)}/></Grid>)}</Grid><Button variant="contained" startIcon={<SaveRounded/>} onClick={submit} disabled={status==='verified'} sx={{mt:3}}>{status==='verified'?'KYC verified':'Submit for review'}</Button></CardContent></Card></Box>;
}
