import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import { listCountries, listStates, listCities } from '../controllers/locationController.js';
import { listPublicProperties, getPublicProperty, listPublicSurveyors, getPublicSurveyor, getPrivateSurveyor, listPublicSurveyServices, listPublicSurveyJobs, searchPublicMarketplace, streamPublicPropertyMedia } from '../controllers/publicController.js';
const router = Router();
const searchLimiter = rateLimit({ windowMs: 60 * 1000, limit: 90, standardHeaders: true, legacyHeaders: false });
router.get('/search', searchLimiter, searchPublicMarketplace);
router.get('/locations/countries', listCountries);
router.get('/locations/states', listStates);
router.get('/locations/cities', listCities);
router.get('/property-media/:id/content', streamPublicPropertyMedia);
router.get('/properties', listPublicProperties);
router.get('/properties/:id', getPublicProperty);
router.get('/surveyors', listPublicSurveyors);
router.get('/surveyors/:id', getPublicSurveyor);
router.get('/surveyor-private/:id', getPrivateSurveyor);
router.get('/survey-services', listPublicSurveyServices);
router.get('/survey-jobs', listPublicSurveyJobs);
export default router;
